[package]
name = "plum"
version = "0.1.0"
authors = ["Yasuaki Uechi <y@uechi.io>"]

[dependencies]
wasm-bindgen = "0.2.48"
cfg-if = "0.1.9"
tensorflow = "0.13.0"

[dev-dependencies]
wasm-bindgen-test = "0.2.48"

[lib]
crate-type = ["cdylib", "rlib"]
