[package]
name = "plum"
version = "0.1.0"
authors = ["Yasuaki Uechi <y@uechi.io>"]

[dependencies]
wasm-bindgen = "0.2.51"
cfg-if = "0.1.10"
tensorflow = "0.14.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.1"

[lib]
crate-type = ["cdylib", "rlib"]
